[manifest]
version = "1.0.0"
dump_lua = true
priority = 0







[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "tab_definition_function = create_UIBox_current_hands,"
position = "after"
payload = '''
},
{
    label = 'Zodiacs',
    tab_definition_function = create_UIBox_zodiacs,

'''
match_indent = true
times = 1


